# Generated by Django 4.2 on 2023-05-18 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backShProject", "0002_remove_post_image_post_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="fcm_token",
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
    ]
