# Generated by Django 4.2 on 2023-05-18 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backShProject', '0003_post_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='community_photos/'),
        ),
    ]
